### ISSUE TITLE
Deploy new Jupyter authentication logic

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/Jupyter-Authenticator#31]
Deploying the new authenticator will require restarting the JupyterHub service. To minimize the impact of this disruption, deployment should take place during regularly scheduled system maintenance. 

#### Todo:
- [ ] Mark a new GitHub release
- [ ] Push the package to any necessary package repositories
- [ ] Install the authenticator on the deployment server
  - [ ] `pip` install the package
  - [ ] Update the Jupyter config files
  - [ ] Restart the Jupyter service
- [ ] Manually test the authentication process to ensure things are working. Iterate fixes as necessary.
- [ ] Update the docs with anything new that was learned
